Testing potential fix due to Github Pages Liquid version
All local testing has been with Liquid 2.2.2, but Github uses an
earlier version and results in a
"Liquid error: undefined method `include?' for nil:NilClass"
this is just an attempt to achieve the same result a different way.
Don't know if it will fix it though.